[profile.default]
src = 'contracts'
out = 'artifacts_forge'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
remappings = ["@openzeppelin/=node_modules/@openzeppelin/", "forge-std/=lib/forge-std/src/", "@root/=contracts/"]