/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as miniMeTokenSol from "./MiniMeToken.sol";
export type { miniMeTokenSol };
export type { Controlled } from "./Controlled";
export type { TokenController } from "./TokenController";
