/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IArbitrable,
  IArbitrableInterface,
} from "../../../../../../@kleros/kleros-interaction/contracts/standard/arbitration/IArbitrable";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "_disputeID",
        type: "uint256",
      },
      {
        name: "_ruling",
        type: "uint256",
      },
    ],
    name: "rule",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "_metaEvidenceID",
        type: "uint256",
      },
      {
        indexed: false,
        name: "_evidence",
        type: "string",
      },
    ],
    name: "MetaEvidence",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "_arbitrator",
        type: "address",
      },
      {
        indexed: true,
        name: "_disputeID",
        type: "uint256",
      },
      {
        indexed: false,
        name: "_metaEvidenceID",
        type: "uint256",
      },
      {
        indexed: false,
        name: "_evidenceGroupID",
        type: "uint256",
      },
    ],
    name: "Dispute",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "_arbitrator",
        type: "address",
      },
      {
        indexed: true,
        name: "_evidenceGroupID",
        type: "uint256",
      },
      {
        indexed: true,
        name: "_party",
        type: "address",
      },
      {
        indexed: false,
        name: "_evidence",
        type: "string",
      },
    ],
    name: "Evidence",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "_arbitrator",
        type: "address",
      },
      {
        indexed: true,
        name: "_disputeID",
        type: "uint256",
      },
      {
        indexed: false,
        name: "_ruling",
        type: "uint256",
      },
    ],
    name: "Ruling",
    type: "event",
  },
];

export class IArbitrable__factory {
  static readonly abi = _abi;
  static createInterface(): IArbitrableInterface {
    return new utils.Interface(_abi) as IArbitrableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IArbitrable {
    return new Contract(address, _abi, signerOrProvider) as IArbitrable;
  }
}
