/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface MiniMeTokenFactoryInterface extends utils.Interface {
  functions: {
    "createCloneToken(address,uint256,string,uint8,string,bool)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "createCloneToken"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createCloneToken",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<boolean>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "createCloneToken",
    data: BytesLike
  ): Result;

  events: {};
}

export interface MiniMeTokenFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MiniMeTokenFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createCloneToken(
      _parentToken: PromiseOrValue<string>,
      _snapshotBlock: PromiseOrValue<BigNumberish>,
      _tokenName: PromiseOrValue<string>,
      _decimalUnits: PromiseOrValue<BigNumberish>,
      _tokenSymbol: PromiseOrValue<string>,
      _transfersEnabled: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  createCloneToken(
    _parentToken: PromiseOrValue<string>,
    _snapshotBlock: PromiseOrValue<BigNumberish>,
    _tokenName: PromiseOrValue<string>,
    _decimalUnits: PromiseOrValue<BigNumberish>,
    _tokenSymbol: PromiseOrValue<string>,
    _transfersEnabled: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createCloneToken(
      _parentToken: PromiseOrValue<string>,
      _snapshotBlock: PromiseOrValue<BigNumberish>,
      _tokenName: PromiseOrValue<string>,
      _decimalUnits: PromiseOrValue<BigNumberish>,
      _tokenSymbol: PromiseOrValue<string>,
      _transfersEnabled: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    createCloneToken(
      _parentToken: PromiseOrValue<string>,
      _snapshotBlock: PromiseOrValue<BigNumberish>,
      _tokenName: PromiseOrValue<string>,
      _decimalUnits: PromiseOrValue<BigNumberish>,
      _tokenSymbol: PromiseOrValue<string>,
      _transfersEnabled: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createCloneToken(
      _parentToken: PromiseOrValue<string>,
      _snapshotBlock: PromiseOrValue<BigNumberish>,
      _tokenName: PromiseOrValue<string>,
      _decimalUnits: PromiseOrValue<BigNumberish>,
      _tokenSymbol: PromiseOrValue<string>,
      _transfersEnabled: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
