/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IEvidence__factory } from "./IEvidence__factory";
export { IMetaEvidence__factory } from "./IMetaEvidence__factory";
