/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Arbitrable } from "./Arbitrable";
export type { Arbitrator } from "./Arbitrator";
export type { IArbitrable } from "./IArbitrable";
